version: '3.7'

services:

#  web-app:
#    container_name: web-app
#    restart: always
#    build:
#      context: ./
#      dockerfile: app.dockerfile
#    ports:
#      - "8080:80"
#    links:
#      - "postgres"
#    networks:
#      - internal

  postgres:
    container_name: postgres
    restart: always
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - /usr/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - internal

networks:
  internal:
    driver: bridge