  version: '3.7'

services:

  postgres:
    container_name: 'postgres-container'
    restart: always
    image: postgres
    build:
      context: ./
      dockerfile: postgres.dockerfile
    ports:
      - "localhost:5432"
    volumes:
      - /usr/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_MULTIPLE_DATABASES=exampledb
    networks:
      - internal

networks:
  internal:
    driver: bridge
